FlowerShop/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace FlowerShop.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index() 
        { 
            return View();
        }
    }
}

FlowerShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace FlowerShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index() 
        { 
            return View();
        }
    }
}

FlowerShop/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace FlowerShop.Controllers
{
    public class QuestionController : Controller
    {
        public IActionResult Index() 
        {
            return View();
        }
    }
}

FlowerShop/Controllers/ShopController.cs
using FlowerShop.Data;
using FlowerShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace FlowerShop.Controllers
{
    //[Authorize]
    public class ShopController: Controller
    {
        private readonly FlowerShopDBContext _dbContext;

        private IEnumerable<Product> _products;

        public ShopController(FlowerShopDBContext dBContext)
        {
            _dbContext = dBContext;
            _products = _dbContext.Products;
            
        }

        //display a list of products
        public IActionResult Index() 
        {
            //only returns a product if it isnt deleted
            return View(_products.Where(p => p.Deleted == false));
        }

        //display a single product
        public IActionResult Details(int id) 
        {
            Console.WriteLine(id.ToString());
            //create a product object
            Product product = null;

            //validatd id
            if (id >= 0 ) 
            { 
                product = _products.SingleOrDefault(p => p.Id == id);
            }

            //check product for null value
            if(product == null) 
            { 
                return NotFound();
            }

            return View(product);
        }

    }
}

FlowerShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlowerShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlowerShop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Family Flowers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">FAQs</a>
                        </li>
                    </ul>
                </div>
                <a class="nav-link text-dark" asp-controller="Admin" asp-action="Index">Admin</a><partial name="_LoginPartial.cshtml">
                <a class="nav-link text-primary" asp-controller="ShoppingCart" asp-action="Index">My cart</a>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FlowerShop - <a asp-area="" asp-controller="Contact" asp-action="Index">Contact us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>