FlowerShop/Controllers/ShopController.cs
using FlowerShop.Data;
using FlowerShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace FlowerShop.Controllers
{
    //[Authorize]
    public class ShopController: Controller
    {
        private readonly FlowerShopDBContext _dbContext;

        private IEnumerable<Product> _products;

        public ShopController(FlowerShopDBContext dBContext)
        {
            _dbContext = dBContext;
            _products = _dbContext.Products;
            
        }

        //display a list of products
        public IActionResult Index() 
        {
            //only returns a product if it isnt deleted
            return View(_products.Where(p => p.Deleted == false));
        }

        //display a single product
        public IActionResult Details(int id) 
        {
            Console.WriteLine(id.ToString());
            //create a product object
            Product product = null;

            //validatd id
            if (id >= 0 ) 
            { 
                product = _products.SingleOrDefault(p => p.Id == id);
            }

            //check product for null value
            if(product == null) 
            { 
                return NotFound();
            }

            return View(product);
        }

    }
}

FlowerShop/Controllers/ShoppingCartController.cs
using FlowerShop.Data;
using FlowerShop.Dto;
using FlowerShop.Models;
using FlowerShop.Services;
using FlowerShop.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace FlowerShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        //session with the db
        private readonly FlowerShopDBContext _dbContext;
        private readonly IEmailService _emailService;
        private readonly OrderInfo _orderInfo;
        private decimal _grandTotal = 0.0m;

        public ShoppingCartController(FlowerShopDBContext dBContext, IEmailService emailService)
        {
            _dbContext = dBContext;
            _emailService = emailService;
            _orderInfo = _dbContext.OrderInfos.SingleOrDefault(o => o.Id == 1);
            
        }

        public IActionResult Index()
        {

            List<ShoppingCart> cartItems = _dbContext.ShoppingCarts
                .Include(c => c.Product)
                .ToList();

            foreach (ShoppingCart item in cartItems)
            {
                _grandTotal += item.GetTotal();
            }

            //create a new view model
            CartListWithGrandTotal cartListWithGrandTotal = new()
            {
                ShoppingCarts = cartItems,
                OrderTotal = (_grandTotal * 1.1m)
            };

            return View(cartListWithGrandTotal);
        }

        public IActionResult AddToCart(int productId)
        {
            Product product = _dbContext.Products.Find(productId);

            if (product == null)
            {
                return NotFound();
            }

            OrderInfo currentOrder = GetCurrentOrder();

            ShoppingCart existingCartItem = _dbContext.ShoppingCarts
                .SingleOrDefault(c => c.ProductId == productId && c.OrderInfoId == currentOrder.Id);

            if (existingCartItem != null)
            {
                existingCartItem.Quantity++;
            }
            else
            {
                int shippingAddressId = GetDefaultShippingAddressId(currentOrder.CustomerId);

                ShoppingCart newCartItem = new ShoppingCart
                {
                    OrderInfoId = currentOrder.Id,
                    ProductId = productId,
                    Quantity = 1,
                    Deleted = false,
                    Product = product,
                    OrderInfo = currentOrder
                };

                _dbContext.ShoppingCarts.Add(newCartItem);
            }

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int cartItemId)
        {
            ShoppingCart cartItem = _dbContext.ShoppingCarts.Find(cartItemId);

            if (cartItem != null)
            {
                // Decrease the quantity, and remove the item if quantity becomes zero
                if (cartItem.Quantity > 1)
                {
                    cartItem.Quantity--;
                }
                else
                {
                    _dbContext.ShoppingCarts.Remove(cartItem);
                }

                _dbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult AddToCartFromReceipt(int receiptItemId)
        {
            Product product = _dbContext.Products.Find(receiptItemId);

            if (product == null)
            {
                return NotFound();
            }

            OrderInfo currentOrder = GetCurrentOrder();

            ShoppingCart existingCartItem = _dbContext.ShoppingCarts
                .SingleOrDefault(c => c.ProductId == receiptItemId && c.OrderInfoId == currentOrder.Id);

            if (existingCartItem == null)
            {
                return NotFound();
            }

            existingCartItem.Quantity++;

            //_dbContext.ShoppingCarts.Add(existingCartItem);

            _dbContext.SaveChanges();

            return RedirectToAction("Index");

        }

        public IActionResult DeleteCart()
        {

            int currentCustomerId = GetCurrentCustomerId();

            // Find all items in the shopping cart associated with the current customer
            List<ShoppingCart> cartItems = _dbContext.ShoppingCarts
                .Where(c => c.OrderInfo.CustomerId == currentCustomerId)
                .ToList();

            // Remove all items from the shopping cart
            _dbContext.ShoppingCarts.RemoveRange(cartItems);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");

        }

        public IActionResult ConfirmOrder() 
        {
            List<ShoppingCart> cartItems = _dbContext.ShoppingCarts
                .Include(c => c.Product)
                .ToList();

            foreach (ShoppingCart item in cartItems)
            {
                _grandTotal += item.GetTotal();
            }

            //create a new view model
            CartListWithGrandTotal cartListWithGrandTotal = new()
            {
                ShoppingCarts = cartItems,
                OrderTotal = (_grandTotal * 1.1m)
            };

            if(cartListWithGrandTotal.ShoppingCarts.Count>0) 
            {
                _emailService.SendEmail(cartListWithGrandTotal);
            }
    
            //clear cart 
            int currentCustomerId = GetCurrentCustomerId();

            // Find all items in the shopping cart associated with the current customer
            List<ShoppingCart> cartItem = _dbContext.ShoppingCarts
                .Where(c => c.OrderInfo.CustomerId == currentCustomerId)
                .ToList();

            if(cartItem.Count>0) 
            {
                // Remove all items from the shopping cart
                _dbContext.ShoppingCarts.RemoveRange(cartItems);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return Json("Your cart is Empty");
            
        }

        private OrderInfo GetCurrentOrder()
        {
            int customerId = GetCurrentCustomerId();

            OrderInfo currentOrder = _dbContext.OrderInfos
                .Include(o => o.OrderState)
                .Include(o => o.ShippingAddress)
                .Include(o => o.Customer)
                .Include(o => o.ShoppingCarts)
                .FirstOrDefault(o => o.CustomerId == customerId && o.OrderState.Name == "Active");

            if (currentOrder == null)
            {
                int shippingAddressId = GetDefaultShippingAddressId(customerId);

                currentOrder = new OrderInfo
                {
                    CustomerId = customerId,
                    Date = DateTime.Now,
                    OrderStateId = GetPendingOrderStateId(),
                    ShippingAddressId = shippingAddressId
                };

                _dbContext.OrderInfos.Add(currentOrder);
                _dbContext.SaveChanges();
            }

            return currentOrder;
        }

        private int GetCurrentCustomerId()
        {
            // Implement this method based on your authentication logic.
            // For example, if you're using ASP.NET Identity, you might retrieve the current user's ID.
            // Alternatively, if you have a custom authentication system, adjust this method accordingly.
            // Example: Replace with actual logic to get the current customer ID.
            return 1;

        }

        private int GetPendingOrderStateId()
        {
            return _dbContext.OrderStates
                .FirstOrDefault(os => os.Name == "Pending")?.Id ?? 0;
        }

        private int GetDefaultShippingAddressId(int customerId)
        {
            return _dbContext.ShippingAddresses
                .Where(sa => sa.CustomerId == customerId && sa.Deleted == false)
                .Select(sa => sa.Id)
                .FirstOrDefault();
        }


    }

}

FlowerShop/Views/Shop/Details.cshtml
@model Product
@{

}

<div class="card" style="width: 18rem;">

    @* test which product name got passed to the view to load corresponding image *@.
    @if (Model.Name == "Roses")
    {
        <img class="card-img-top" src="/css/sidney-pearce-yPMJliKzyc4-unsplash.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Rose")
    {
        <img class="card-img-top" src="/css/Rose.jpg" alt="Card image cap">
    }
    else if(Model.Name =="Toy")
    {
        <img class="card-img-top" src="/css/june-gathercole-CDt2jVuSkh4-unsplash.jpg" alt="Card image cap">
    }
    else if(Model.Name =="Tulips")
    {
        <img class="card-img-top" src="/css/catia-climovich-Z-6bfsa6rD8-unsplash.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Tulip")
    {
        <img class="card-img-top" src="/css/SingleTul.jpg" alt="Card image cap">
    }
    else if(Model.Name =="Carnations")
    {
        <img class="card-img-top" src="/css/sidney-pearce-qz3T7J-M-Co-unsplash.jpg" alt="Card image cap">
    }
    else if(Model.Name =="Daysies")
    {
        <img class="card-img-top" src="/css/larisa-birta-WIaFt0JeGMA-unsplash.jpg" alt="Card image cap">
    }
    else if(Model.Name =="Greeting Cards")
    {
        <img class="card-img-top" src="/css/sydney-rae-qZXxmajoHx0-unsplash.jpg" alt="Card image cap">
    }
    else if(Model.Name =="Gift Card")
    {
        <img class="card-img-top" src="/css/GiftC.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Balloon")
    {
        <img class="card-img-top" src="/css/adi-goldstein-Hli3R6LKibo-unsplash.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Gift in a box")
    {
        <img class="card-img-top" src="/css/Chocolates.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Box of Cookies")
    {
        <img class="card-img-top" src="/css/Cookies.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Gift Basket")
    {
        <img class="card-img-top" src="/css/GiftBask.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Gift Basket Eddible")
    {
        <img class="card-img-top" src="/css/EddibleBask.jpg" alt="Card image cap">
    }
    else if(Model.Name == "Wine")
    {
        <img class="card-img-top" src="/css/Wine.jpg" alt="Card image cap">
    }

    <div class="card-body">
        <h5 class="card-title">@Model.Name @Model.ProductType</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc.</p>
        <p>Price @Model.Price</p>
        <a asp-controller="Shop" asp-action="Index">Shop</a>
        <a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-productId="@Model.Id">Add to Cart</a>
    </div>
</div>

FlowerShop/Views/Shop/Index.cshtml
@model IEnumerable<Product>
@{
   
}

<h2 class="text-primary text-center">Please browse our catalog</h2>

<div class="card-container">
    @foreach (Product product in Model)
    {
        <div class="card">
            @* test which product name got passed to the view to load corresponding image *@.
            @if (product.Name == "Roses")
            {
                <img class="card-img-top" src="/css/sidney-pearce-yPMJliKzyc4-unsplash.jpg" alt="Card image cap">
            }
            else if (product.Name == "Toy")
            {
                <img class="card-img-top" src="/css/june-gathercole-CDt2jVuSkh4-unsplash.jpg" alt="Card image cap">
            }
            else if (product.Name == "Tulips")
            {
                <img class="card-img-top" src="/css/catia-climovich-Z-6bfsa6rD8-unsplash.jpg" alt="Card image cap">
            }
            else if (product.Name == "Carnations")
            {
                <img class="card-img-top" src="/css/sidney-pearce-qz3T7J-M-Co-unsplash.jpg" alt="Card image cap">
            }
            else if (product.Name == "Daysies")
            {
                <img class="card-img-top" src="/css/larisa-birta-WIaFt0JeGMA-unsplash.jpg" alt="Card image cap">
            }
            else if (product.Name == "Greeting Cards")
            {
                <img class="card-img-top" src="/css/sydney-rae-qZXxmajoHx0-unsplash.jpg" alt="Card image cap">
            }
            else if (product.Name == "Gift Card")
            {
                <img class="card-img-top" src="/css/GiftC.jpg" alt="Card image cap">
            }
            else if (product.Name == "Balloon")
            {
                <img class="card-img-top" src="/css/adi-goldstein-Hli3R6LKibo-unsplash.jpg" alt="Card image cap">
            }
            else if(product.Name == "Rose")
            {
                <img class="card-img-top" src="/css/Rose.jpg" alt="Card image cap">
            }
            else if(product.Name == "Tulip")
            {
                <img class="card-img-top" src="/css/SingleTul.jpg" alt="Card image cap">
            }
            else if(product.Name == "Gift in a box")
            {
                <img class="card-img-top" src="/css/Chocolates.jpg" alt="Card image cap">
            }
            else if(product.Name == "Wine")
            {
                <img class="card-img-top" src="/css/Wine.jpg" alt="Card image cap">
            }
            else if(product.Name =="Gift Basket Eddible")
            {
                <img class="card-img-top" src="/css/EddibleBask.jpg" alt="Card image cap">
            }
            else if(product.Name == "Gift Basket")
            {
                <img class="card-img-top" src="/css/GiftBask.jpg" alt="Card image cap">
            }
            else if(product.Name == "Box of Cookies")
            {
                <img class="card-img-top" src="/css/Cookies.jpg" alt="Card image cap">
            }
            else
            {
                <img class="card-img-top" src="/css/ioann-mark-kuznietsov-eHlVZcSrjfg-unsplash.jpg" alt="stock flower image">
            }
            
            <h5 class="card-title">@product.Name</h5>
            <p class="card-text">@product.Description</p>
            <p>Price : $@product.Price</p>
            <div style="height: 100%"></div>
            <a asp-controller="Shop" asp-action="Details" asp-route-id="@product.Id">Details</a>
            <a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-productId="@product.Id">Add to Cart</a>
        </div>
    }
</div>